// const jobs = [
//   {
//     "id": 1,
//     "title": "Web Developer",
//     "work_address": "12345 main street",
//     "city": "Los Angeles",
//     "_state": "CA",
//     "zip": "12345",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "100000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Google",
//     "date_posted": "2022-01-28"
//   },
//   {
//     "id": 2,
//     "title": "Electrician",
//     "work_address": "22345 1st street",
//     "city": "Orlando",
//     "_state": "FL",
//     "zip": "12346",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "105000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "CAT",
//     "date_posted": "2022-02-28"
//   },
//   {
//     "id": 3,
//     "title": "Accountant",
//     "work_address": "12345 main lane",
//     "city": "New York City",
//     "_state": "NY",
//     "zip": "12745",
//     "job_location": "In office",
//     "job_type": "Internship",
//     "salary": "42000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Home Depot",
//     "date_posted": "2022-01-15"
//   },
//   {
//     "id": 4,
//     "title": "Acountant",
//     "work_address": "12345 main street",
//     "city": "Los Angeles",
//     "_state": "CA",
//     "zip": "12345",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "70000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Amazon",
//     "date_posted": "2022-03-28"
//   },
//   {
//     "id": 5,
//     "title": "Web Developer",
//     "work_address": "12345 main street",
//     "city": "Los Angeles",
//     "_state": "CA",
//     "zip": "12345",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "100000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Google",
//     "date_posted": "2022-01-28"
//   },
//   {
//     "id": 6,
//     "title": "Web Developer",
//     "work_address": "12345 main street",
//     "city": "Los Angeles",
//     "_state": "CA",
//     "zip": "12345",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "100000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Google",
//     "date_posted": "2022-01-28"
//   },
//   {
//     "id": 7,
//     "title": "Web Developer",
//     "work_address": "12345 main street",
//     "city": "Los Angeles",
//     "_state": "CA",
//     "zip": "12345",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "100000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Google",
//     "date_posted": "2022-01-28"
//   },
//   {
//     "id": 8,
//     "title": "Web Developer",
//     "work_address": "12345 main street",
//     "city": "Los Angeles",
//     "_state": "CA",
//     "zip": "12345",
//     "job_location": "In office",
//     "job_type": "Full-time",
//     "salary": "100000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Walgreens",
//     "date_posted": "2022-01-28"
//   },
//   {
//     "id": 9,
//     "title": "Web Developer",
//     "work_address": "345 acorn street",
//     "city": "Dallas",
//     "_state": "TX",
//     "zip": "32345",
//     "job_location": "Remote",
//     "job_type": "Contract",
//     "salary": "90000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Walmart",
//     "date_posted": "2022-03-20"
//   },
//   {
//     "id": 10,
//     "title": "Web Developer",
//     "work_address": "12345 2nd street",
//     "city": "Austin",
//     "_state": "TX",
//     "zip": "12385",
//     "job_location": "In office",
//     "job_type": "Part-time",
//     "salary": "40000",
//     "_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisl pellentesque, fermentum eros nec, fringilla libero. Aenean et imperdiet justo. Cras rutrum massa ut dui congue, eu pharetra velit sodales. Vestibulum pharetra diam velit, eget molestie felis semper a. Fusce viverra gravida nulla, eget volutpat lectus auctor nec. Sed sed sodales metus. Nam a ante est. Nulla cursus magna a elit ullamcorper, in blandit elit lacinia. Donec lacinia lectus id lorem tincidunt ornare.",
//     "company_name": "Fred Meyer",
//     "date_posted": "2022-03-29"
//   }
// ]

// export default DATA